### ISSUE TITLE
matlab AM modulation

### ISSUE THREAD

**Issue by 12xi** [MuSAELab/amplitude-modulation-analysis-matlab#11]
ts=0.0025;%信号抽样间隔
t=0:ts:10-ts;%时间矢量
fs=1/ts;%抽样频率
df=fs/length(t);%频率分辨率
msg=randi([-3,3],[100,1]);%消息序列
msg1=msg*ones(1,fs/10);%扩展成取样信号序列
msg2=reshape(msg1.',1,length(t));
Pm=fft(msg2)/fs;
f=-fs/2:df:fs/2-df;
subplot(2,1,1);plot(f,fftshift(abs(Pm)));
title('消息信号频谱');
A=4;
fc=100;
Sam=(A+msg2).*cos(2*pi*fc*t);
Pam=fft(Sam)/fs;
subplot(2,1,2);plot(f,fftshift(abs(Pam)));
title('AM信号频谱');
axis([-200 200 0 5]);
Pc=sum(abs(Sam).^2)/length(Sam);
Ps=Pc-A^2/2;
eta=Ps/Pc;
Dear friends,how to understand the sixth and seventh lines of code?
I can not understand those,I would appreciate if you can help me.

**Comment by rcassani** [comment]
@12xi, this issue does not seem related to the [amplitude-modulation-analysis-matlab](https://github.com/MuSAELab/amplitude-modulation-analysis-matlab)

The code you provided is not in the repository, and it does not use any of the functions in the repository. As such, I'm closing this issue.
